// Generated by FlutterFire CLI — replace this file by running:
//   flutterfire configure
// after setting up your Firebase project.
//
// Until then, this placeholder prevents compilation errors.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run flutterfire configure to generate the correct options.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_S5iLO62loO-IkNWfJkY20Fpq0qS3ghA',
    appId: '1:369260883854:android:399ba34d28cbcf9f5d3edf',
    messagingSenderId: '369260883854',
    projectId: 'brigde',
    storageBucket: 'brigde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV2GY0KU3N3VEZZ4Iyn3UmkGfHESyvWBg',
    appId: '1:369260883854:ios:a1e2a8b6d98fb9b95d3edf',
    messagingSenderId: '369260883854',
    projectId: 'brigde',
    storageBucket: 'brigde.firebasestorage.app',
    iosClientId: '369260883854-5c5ge47oqjk7st14nlsc352h23tpsmp4.apps.googleusercontent.com',
    iosBundleId: 'com.bridge.bridge',
  );

}